# Generated by Django 4.1.2 on 2022-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Indoor", "Indoor"), ("Out Door", "Out Door")],
                max_length=200,
                null=True,
            ),
        ),
    ]
